# Generated by Django 3.0.5 on 2020-04-17 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Masyarakat',
            fields=[
                ('nik', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=35)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=32)),
                ('telp', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id_pengaduan', models.AutoField(primary_key=True, serialize=False)),
                ('tgl_pengaduan', models.DateField()),
                ('isi_laporan', models.TextField()),
                ('foto', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('belum', '0'), ('sedang', 'Proses'), ('sudah', 'Selesai')], max_length=20, unique=True)),
                ('nik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.Masyarakat')),
            ],
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id_petugas', models.AutoField(primary_key=True, serialize=False)),
                ('nama_petugas', models.CharField(max_length=35)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=32)),
                ('telp', models.CharField(max_length=13)),
                ('level', models.CharField(choices=[('admin', 'Admin'), ('petugas', 'Petugas')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tanggapan',
            fields=[
                ('id_tanggapan', models.AutoField(primary_key=True, serialize=False)),
                ('tgl_tanggapan', models.DateField()),
                ('tanggapan', models.TextField()),
                ('id_pengaduan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.Pengaduan')),
                ('id_petugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.Petugas')),
            ],
        ),
    ]
